<a href="https://colab.research.google.com/github/khojiakbar05/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [5]:
print(pd.__version__) # versiyasini korish

2.2.3

In [11]:
mydataset = {
    'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', "BMW"], # - keys
    'counts': [3, 7, 8, 3, 4, 5, 9]  # - values
}

# print(mydataset)
# print("============")

df = pd.DataFrame(mydataset)   # dataFrame bu malumotlarni(dictionary)ni TABLE korinishida shakillantirib beradi indexlarni ham qoyadi
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       8
3    Tesla       3
4  Ferrari       4
5     Ford       5
6      BMW       9

In [15]:
df.head(6)    # tableni boshidan (default) 5 ta malumotn olib beradi ||
#  nechasini korsatishni yozsak boladi ||
#  (-1) -  qoysak tableni hammasini oxiridagi raw dan tashqari korsatadi ||
#  (0)  - qoysak table nomini ozini korsatadi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       8
3    Tesla       3
4  Ferrari       4
5     Ford       5

In [18]:
df.tail()
# oxiridan (default) 5 tasini korsatadi
#  nechasini korsatishni yozsak boladi ||
#  (-1) -  qoysak tableni hammasini boshidagi raw dan tashqari korsatadi ||
#  (0)  - qoysak table nomini ozini korsatadi

      cars  counts
2     Ford       8
3    Tesla       3
4  Ferrari       4
5     Ford       5
6      BMW       9

In [19]:
df.shape  # tableni qator va ustunlar sonini aniqlab beradi

(7, 2)

In [20]:
df.columns    # columnlar nomini va dataTypeni aytadi

Index(['cars', 'counts'], dtype='object')

In [22]:
df.dtypes     # hamma columnlarni typeni korsatadi

cars      object
counts     int64
dtype: object

In [24]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       8
3    Tesla       3
4  Ferrari       4
5     Ford       5
6      BMW       9

In [25]:
df.describe()   # numerical columns only raqamlar statistikasini beradi

# count - qator soni
# mean  - countlarni qoshib qaotiga boladi
# standart deviasion - raqamlarni bir biriga o'xshashligini aniqlaydi
# min - raqamlarni ichida eng kichigini oladi
# 25% - raqamlarni tartiblaydi va bu raqamlarni 25% i 2.5 dan kichik
# 50% - 50%raqamlar 3 ga teng yoki kichick (middle value)
# 75% - 75%raqamlar 7.5 ga teng yoki kichick
# max - raqamlarni ichida eng kattasi oladi

         counts
count  7.000000
mean   5.571429
std    2.439750
min    3.000000
25%    3.500000
50%    5.000000
75%    7.500000
max    9.000000

In [26]:
df.describe(include="all") # har bitta qatorni describe qilib beradi va kop ishlatilmaydi

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  5.571429
std     NaN  2.439750
min     NaN  3.000000
25%     NaN  3.500000
50%     NaN  5.000000
75%     NaN  7.500000
max     NaN  9.000000

In [31]:
df.iloc[1:3]
# 1-value(include) 2-value(exclude) : 1, 2
# qaysi indeksni yozsak osha qatorni nomini va qatorini chiqazib beradi
# -1  bolsa oxiridagi qiymatni chiqazib beradi

    cars  counts
1  Volvo       7
2   Ford       8

In [36]:
df.loc[2:5, "cars"]
# tableni hohlagan qator yoki ustunidagi malumotlarni olamiz
# : - hamma malumotlar
# qatordagi malumotlarni olib beradi

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [40]:
df[df["cars"] == "BMW"]
# bu 3 dan katta bolgan datalani qaytaradi

  cars  counts
0  BMW       3
6  BMW       9

In [43]:
# df.mean(numeric_only=True)
# raqamlarning o'rtachasi
df["counts"].mean()
# bu usulda ham ishlatishimiz mumkin

np.float64(5.571428571428571)

In [44]:
df.sum()
# yig'indini hisoblab beradi

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 39
dtype: object

In [45]:
df.min()
# minimumini topib beradi

cars      BMW
counts      3
dtype: object

In [46]:
df.max()
# maximumini topib beradi

cars      Volvo
counts        9
dtype: object

In [47]:
df.median(numeric_only=True)
# middle valueni olib beradi

counts    5.0
dtype: float64

In [48]:
df.count()
# null valueni chiqazib beradi

cars      7
counts    7
dtype: int64

In [49]:
df.std(numeric_only=True)
# standart deviationni chiqazib beradi

counts    2.43975
dtype: float64

In [50]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", "Ford"],
    "counts": [3, 5, None, 3, 2, None]
}

df.missing = pd.DataFrame(data_with_missing)

print(df.missing)

      cars  counts
0      BMW     3.0
1    Volvo     5.0
2     None     NaN
3    Tesla     3.0
4  Ferrari     2.0
5     Ford     NaN

/tmp/ipykernel_4420/1136634804.py:6: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.missing = pd.DataFrame(data_with_missing)

In [53]:
df.missing.isnull().sum()
# bu booleanda chiqazib beradi
# .sum() nullarni hisoblab olib beradi

cars      1
counts    2
dtype: int64

In [57]:
df.missing.dropna(subset=['counts'])
# null bolgan qiymat qatorlarni tushurib qoldiradi
# (how="all") qatori bilan ochirib tashlaydi
# (axis=1) - qaysi columnda malumot yoq bolsa o'shani ochirib tashlaydi

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [61]:
# df.missing.fillna('unknown')
# data yoq bolgan qaotlarga qiymat qoshib beradi

df.missing.fillna({'cars': "unknown", "counts": 0})
# carsga unknown || countsga 0 qoyib beradi

      cars  counts
0      BMW     3.0
1    Volvo     5.0
2  unknown     0.0
3    Tesla     3.0
4  Ferrari     2.0
5     Ford     0.0

In [64]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head(30)

# df = pd.read_exec("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S

In [70]:
df.to_json("test.json")

In [71]:
# Series => 1D arraylar bilan ishlatilinadi

cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [72]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', 'Ford']